apiVersion: v1
kind: Secret
metadata:
  name: backend-env
type: Opaque
stringData:
  DATABASE_URL: "postgresql://root:your_postgres_password@medcore-db:5432/medcore_hms"
  JWT_SECRET: "change_this_secret_in_prod"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRE_MINUTES: "480"
  APP_CORS_ORIGINS: "http://medcore.local,http://localhost"
